export const MOVIE_URL = 'https://api.nomoreparties.co';
export const ERR = 'Произошла ошибка';
export const EMPTY = 'Ничего не найдено';
export const ERR_REGISTRATION = 'Произошла ошибка при регистрации. Возможно, такой пользователь уже существует';
export const ERR_LOGIN = 'Неправильный email или пароль.';
export const ERR_USERINFO = 'Произошла ошибка при загрузке карточек или данных пользователя';
export const ERR_UPDATEUSER = 'При изменении данных пользователя произошла ошибка';
export const ERR_GETMOVIE = 'Во время запроса произошла ошибка. Возможно, проблема с соединением или сервер недоступен. Подождите немного и попробуйте ещё раз.';
export const MESSAGE_OK = 'Данные успешно изменены.';